# Generated by Django 4.2.30 on 2026-08-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondary_email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
